networks:
  nifi-airflow:
    driver: bridge

services:
  # zookeeper-nifi: # the configuration manager
  #   image: bitnami/zookeeper
  #   hostname: zookeeper-nifi
  #   container_name: zookeeper-nifi
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - nifi-airflow

  nifi-api:
    image: apache/nifi
    hostname: nifi-api
    container_name: nifi-api
    ports:
      - 8443:8443
    environment:
      - NIFI_WEB_HTTP_PORT=8443
    #   - NIFI_CLUSTER_IS_NODE=true
    #   - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
    #   - NIFI_ZK_CONNECT_STRING=zookeeper-nifi:2181
    #   - NIFI_ELECTION_MAX_WAIT=1 min
    #   - NIFI_SENSITIVE_PROPS_KEY=012345678910
    networks:
      - nifi-airflow
    # volumes:
    #   - ./nifi:/data

  postgres-end:
    image: postgres
    hostname: postgres-end
    container_name: postgres-end
    shm_size: 4gb
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    networks:
      - nifi-airflow
